### ISSUE TITLE
IndexError: list index out of range nonostante il sito tntvillage risponda

### ISSUE THREAD

**Issue by bedinsky** [jacopo-j/tnt-downloader#18]
python ./tnt-downloader.py "rick and morty"
Caricamento dati in corso...
Traceback (most recent call last):
  File "./tnt-downloader.py", line 337, in <module>
    main()
  File "./tnt-downloader.py", line 333, in main
    do_search(args.query, chunks_size)
  File "./tnt-downloader.py", line 121, in do_search
    tot_pages = int(search_tree.xpath(tot_pag_addr)[0])
IndexError: list index out of range

**Comment by bedinsky** [comment]
Grazie, la lista adesso funziona ma credo ci sia ancora un problema sul download
