### ISSUE TITLE
errore sul download del torrent

### ISSUE THREAD

**Issue by bedinsky** [jacopo-j/tnt-downloader#19]
python ./tnt-downloader.py "rick and morty"
Caricamento dati in corso...

... viene presentata la lista, inserisco il numero del torrent e dopo invio ricevo in console questo errore

Traceback (most recent call last):
  File "./tnt-downloader.py", line 343, in <module>
    main()
  File "./tnt-downloader.py", line 339, in main
    do_search(args.query, chunks_size)
  File "./tnt-downloader.py", line 299, in do_search
    disp = result.headers['content-disposition']
  File "/usr/local/lib/python2.7/dist-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-disposition'

**Comment by bedinsky** [comment]
Grazie !
