### ISSUE TITLE
 UnicodeEncodeError

### ISSUE THREAD

**Issue by cfwoo** [jacopo-j/tnt-downloader#3]
Traceback (most recent call last):
  File "./tnt-downloader.py", line 268, in <module>
    main()
  File "./tnt-downloader.py", line 264, in main
    do_search(args.query, chunks_size)
  File "./tnt-downloader.py", line 149, in do_search
    title_str.format(row.xpath(title_addr)[0].strip())))
UnicodeEncodeError: 'ascii' codec can't encode character '\u2013' in position 16: ordinal not in range(128)

**Comment by jacopo-j** [comment]
Fornisci queste informazioni per favore:
* sistema operativo
* versione del sistema operativo
* versione di Pyhton
